name: Deploy to GitHub Pages

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  test-deploy:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Test build website
        run: yarn build
  deploy:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
      - uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACD7sNIF08rd7qEDi1Mnt3rhlwobTN2Hnwp+wvlNTijp1AAAAJi5GrgBuRq4AQAAAAtzc2gtZWQyNTUxOQAAACD7sNIF08rd7qEDi1Mnt3rhlwobTN2Hnwp+wvlNTijp1AAAAEClvYMdTjadB2h73O5lMNgJqkMXKXds5drWAYTCPnAnR/uw0gXTyt3uoQOLUye3euGXChtM3YefCn7C+U1OKOnUAAAAFXBvdXJ5YS5saDk2QGdtYWlsLmNvbQ==
      - name: Deploy to GitHub Pages
        env:
          USE_SSH: true
        run: |
          git config --global user.email "pourya.lh96@gmail.com"
          git config --global user.name "Alihosseyni96"
          yarn install --frozen-lockfile
          yarn deploy